/* Generated By:JavaCC: Do not edit this line. langJavaShConstants.java */
package cc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface langJavaShConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int INCREMENT = 6;
  /** RegularExpression Id. */
  int DECREMENT = 7;
  /** RegularExpression Id. */
  int MINUS = 8;
  /** RegularExpression Id. */
  int MULTIPLY = 9;
  /** RegularExpression Id. */
  int DIVIDE = 10;
  /** RegularExpression Id. */
  int MATH = 11;
  /** RegularExpression Id. */
  int LogicalDigital = 12;
  /** RegularExpression Id. */
  int And = 13;
  /** RegularExpression Id. */
  int Or = 14;
  /** RegularExpression Id. */
  int LogicalMathOperator = 15;
  /** RegularExpression Id. */
  int Atribute = 16;
  /** RegularExpression Id. */
  int CONSTANT = 17;
  /** RegularExpression Id. */
  int LOGICALCONSTANT = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int AccessMod = 20;
  /** RegularExpression Id. */
  int Extends = 21;
  /** RegularExpression Id. */
  int Implements = 22;
  /** RegularExpression Id. */
  int Return = 23;
  /** RegularExpression Id. */
  int While = 24;
  /** RegularExpression Id. */
  int If = 25;
  /** RegularExpression Id. */
  int Else = 26;
  /** RegularExpression Id. */
  int For = 27;
  /** RegularExpression Id. */
  int Do = 28;
  /** RegularExpression Id. */
  int Int = 29;
  /** RegularExpression Id. */
  int Float = 30;
  /** RegularExpression Id. */
  int String = 31;
  /** RegularExpression Id. */
  int Bool = 32;
  /** RegularExpression Id. */
  int Class = 33;
  /** RegularExpression Id. */
  int Ident = 34;
  /** RegularExpression Id. */
  int CHAR = 35;
  /** RegularExpression Id. */
  int StringLiteralToken = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"++\"",
    "\"--\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<MATH>",
    "<LogicalDigital>",
    "<And>",
    "<Or>",
    "<LogicalMathOperator>",
    "\"=\"",
    "<CONSTANT>",
    "<LOGICALCONSTANT>",
    "<DIGIT>",
    "<AccessMod>",
    "\"extends\"",
    "\"implements\"",
    "\"return\"",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "\"for\"",
    "\"do\"",
    "\"int\"",
    "\"float\"",
    "\"string\"",
    "\"bool\"",
    "\"class\"",
    "<Ident>",
    "<CHAR>",
    "<StringLiteralToken>",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"[]\"",
    "\",\"",
  };

}
